import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft } from "lucide-react";
import { toast } from "sonner";
import { enviarSolicitacaoPrivacidade } from "@/lib/privacidade.functions";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { onlyDigits, maskCpf } from "@/lib/cpf";
import { useServerFn } from "@tanstack/react-start";

export const Route = createFileRoute("/privacidade")({ component: PrivacidadePage });
function PrivacidadePage() { const enviar = useServerFn(enviarSolicitacaoPrivacidade); const [f,setF]=useState({email:"",telefone:"",cpf:"",motivo:""}); const [enviando,setEnviando]=useState(false); async function submit(e:React.FormEvent): Promise<void>{e.preventDefault(); if(onlyDigits(f.cpf).length!==11){toast.error("Informe um CPF válido."); return;} setEnviando(true);try{const r=await enviar({data:{...f,cpf:onlyDigits(f.cpf)}});toast.success(`Solicitação registrada. Protocolo: ${r.protocolo}`);setF({email:"",telefone:"",cpf:"",motivo:""});}catch(err){toast.error(err instanceof Error?err.message:"Não foi possível enviar.");}finally{setEnviando(false);}} return <main className="mx-auto min-h-screen max-w-3xl px-4 py-10"><Link to="/entrar" className="mb-6 inline-flex items-center gap-1 text-sm text-muted-foreground"><ArrowLeft className="size-4" /> Voltar</Link><Card><CardContent className="space-y-6 p-6 text-sm leading-6"><div><h1 className="text-2xl font-bold">Aviso de Privacidade</h1><p className="text-muted-foreground">Control ALL LTDA, versão 19/09/2026</p></div><p>Tratamos os dados necessários para criar a conta, oferecer os módulos escolhidos, proteger acessos, atender solicitações e melhorar a experiência. Não vendemos dados pessoais nem os compartilhamos com terceiros para publicidade.</p><p>Dados financeiros, documentos, fotos e informações de saúde são tratados como conteúdo privado do usuário. Exames são privados por padrão e só podem ser compartilhados com familiares por escolha expressa. Arquivos enviados para análise de layout de fatura são usados exclusivamente para modelagem técnica e têm descarte previsto em até 30 dias.</p><p>Você pode solicitar confirmação, acesso, correção, anonimização, eliminação, informação sobre compartilhamento ou revisão do tratamento. Para segurança, pedimos e-mail, telefone e CPF no formulário abaixo. Contato provisório: <a className="underline" href="mailto:mbdo.matheus@gmail.com">mbdo.matheus@gmail.com</a>.</p><form onSubmit={submit} className="grid gap-3 border-t pt-5"><h2 className="font-semibold">Solicitar exclusão ou outro direito de privacidade</h2><div className="grid gap-3 sm:grid-cols-2"><div><Label>E-mail</Label><Input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})} required /></div><div><Label>Telefone</Label><Input value={f.telefone} onChange={e=>setF({...f,telefone:e.target.value})} required /></div></div><div><Label>CPF</Label><Input inputMode="numeric" value={maskCpf(f.cpf)} onChange={e=>setF({...f,cpf:onlyDigits(e.target.value).slice(0,11)})} required /></div><div><Label>Motivo ou detalhe</Label><Textarea value={f.motivo} onChange={e=>setF({...f,motivo:e.target.value})} /></div><Button disabled={enviando}>{enviando?"Enviando…":"Enviar solicitação"}</Button></form></CardContent></Card></main>; }
