import { useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

export function LegalDialogs({ compact = false }: { compact?: boolean }) {
  const [aberto, setAberto] = useState<"termos" | "privacidade" | null>(null);
  const classe = compact ? "underline underline-offset-4" : "text-sm text-muted-foreground hover:text-foreground";
  return <><button type="button" className={classe} onClick={() => setAberto("termos")}>Termos{compact ? " de Uso" : ""}</button><button type="button" className={classe} onClick={() => setAberto("privacidade")}>Privacidade{compact ? "" : ""}</button><Dialog open={aberto === "termos"} onOpenChange={(v) => !v && setAberto(null)}><DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Termos de Uso</DialogTitle><DialogDescription>Control ALL LTDA, versão 20/09/2026</DialogDescription></DialogHeader><div className="space-y-4 text-sm leading-6"><p>O Control ALL é uma ferramenta de organização pessoal e não substitui orientação financeira, contábil, médica, jurídica ou profissional.</p><p><b>Conta e segurança.</b> Você é responsável pelos dados inseridos, por proteger sua senha e por não compartilhar usuário, convite ou sessão.</p><p><b>Uso permitido.</b> Não é permitido acessar dados de terceiros, contornar controles de segurança, enviar arquivos maliciosos ou afetar a disponibilidade do serviço.</p><p><b>Dados e encerramento.</b> Você pode solicitar exclusão conforme o Aviso de Privacidade. A Control ALL LTDA pode suspender ou encerrar acessos em caso de risco, abuso, obrigação legal ou violação destes termos.</p></div><Button variant="outline" onClick={() => setAberto(null)}>Fechar</Button></DialogContent></Dialog><Dialog open={aberto === "privacidade"} onOpenChange={(v) => !v && setAberto(null)}><DialogContent className="max-h-[85vh] max-w-2xl overflow-y-auto"><DialogHeader><DialogTitle>Aviso de Privacidade</DialogTitle><DialogDescription>Control ALL LTDA, versão 20/09/2026</DialogDescription></DialogHeader><div className="space-y-4 text-sm leading-6"><p>Tratamos dados necessários para criar a conta, oferecer módulos escolhidos, proteger acessos e melhorar a experiência. Não vendemos dados pessoais nem os compartilhamos para publicidade.</p><p>Dados financeiros, documentos, fotos e informações de saúde são conteúdo privado. Exames são privados por padrão e só são compartilhados com familiares mediante escolha expressa.</p><p>Você pode solicitar acesso, correção, anonimização, eliminação, informação sobre compartilhamento ou revisão do tratamento pelo canal <a className="underline" href="mailto:privacidade@controlall.com.br">privacidade@controlall.com.br</a>.</p></div><Button variant="outline" onClick={() => setAberto(null)}>Fechar</Button></DialogContent></Dialog></>;
}
