/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedBackupRouteImport } from './routes/_authenticated/backup'
import { Route as AuthenticatedCartoesRouteImport } from './routes/_authenticated/cartoes'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCompartilharRouteImport } from './routes/_authenticated/compartilhar'
import { Route as AuthenticatedContaRouteImport } from './routes/_authenticated/conta'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedInvestimentosRouteImport } from './routes/_authenticated/investimentos'
import { Route as AuthenticatedListaComprasRouteImport } from './routes/_authenticated/lista-compras'
import { Route as AuthenticatedNovaSenhaRouteImport } from './routes/_authenticated/nova-senha'
import { Route as AuthenticatedPersonalizacaoRouteImport } from './routes/_authenticated/personalizacao'
import { Route as AuthenticatedReceitasRouteImport } from './routes/_authenticated/receitas'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as OauthGoogleDriveReturnRouteImport } from './routes/oauth/google-drive/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBackupRoute = AuthenticatedBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCartoesRoute = AuthenticatedCartoesRouteImport.update({
  id: '/cartoes',
  path: '/cartoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompartilharRoute =
  AuthenticatedCompartilharRouteImport.update({
    id: '/compartilhar',
    path: '/compartilhar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContaRoute = AuthenticatedContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvestimentosRoute =
  AuthenticatedInvestimentosRouteImport.update({
    id: '/investimentos',
    path: '/investimentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListaComprasRoute =
  AuthenticatedListaComprasRouteImport.update({
    id: '/lista-compras',
    path: '/lista-compras',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNovaSenhaRoute = AuthenticatedNovaSenhaRouteImport.update({
  id: '/nova-senha',
  path: '/nova-senha',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalizacaoRoute =
  AuthenticatedPersonalizacaoRouteImport.update({
    id: '/personalizacao',
    path: '/personalizacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReceitasRoute = AuthenticatedReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OauthGoogleDriveReturnRoute = OauthGoogleDriveReturnRouteImport.update({
  id: '/oauth/google-drive/return',
  path: '/oauth/google-drive/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/compartilhar': typeof AuthenticatedCompartilharRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/lista-compras': typeof AuthenticatedListaComprasRoute
  '/nova-senha': typeof AuthenticatedNovaSenhaRoute
  '/personalizacao': typeof AuthenticatedPersonalizacaoRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backup': typeof AuthenticatedBackupRoute
  '/cartoes': typeof AuthenticatedCartoesRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/compartilhar': typeof AuthenticatedCompartilharRoute
  '/conta': typeof AuthenticatedContaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/investimentos': typeof AuthenticatedInvestimentosRoute
  '/lista-compras': typeof AuthenticatedListaComprasRoute
  '/nova-senha': typeof AuthenticatedNovaSenhaRoute
  '/personalizacao': typeof AuthenticatedPersonalizacaoRoute
  '/receitas': typeof AuthenticatedReceitasRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/backup': typeof AuthenticatedBackupRoute
  '/_authenticated/cartoes': typeof AuthenticatedCartoesRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/compartilhar': typeof AuthenticatedCompartilharRoute
  '/_authenticated/conta': typeof AuthenticatedContaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/investimentos': typeof AuthenticatedInvestimentosRoute
  '/_authenticated/lista-compras': typeof AuthenticatedListaComprasRoute
  '/_authenticated/nova-senha': typeof AuthenticatedNovaSenhaRoute
  '/_authenticated/personalizacao': typeof AuthenticatedPersonalizacaoRoute
  '/_authenticated/receitas': typeof AuthenticatedReceitasRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/oauth/google-drive/return': typeof OauthGoogleDriveReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backup'
    | '/cartoes'
    | '/categorias'
    | '/compartilhar'
    | '/conta'
    | '/dashboard'
    | '/despesas'
    | '/importar'
    | '/inicio'
    | '/investimentos'
    | '/lista-compras'
    | '/nova-senha'
    | '/personalizacao'
    | '/receitas'
    | '/usuarios'
    | '/oauth/google-drive/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backup'
    | '/cartoes'
    | '/categorias'
    | '/compartilhar'
    | '/conta'
    | '/dashboard'
    | '/despesas'
    | '/importar'
    | '/inicio'
    | '/investimentos'
    | '/lista-compras'
    | '/nova-senha'
    | '/personalizacao'
    | '/receitas'
    | '/usuarios'
    | '/oauth/google-drive/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/backup'
    | '/_authenticated/cartoes'
    | '/_authenticated/categorias'
    | '/_authenticated/compartilhar'
    | '/_authenticated/conta'
    | '/_authenticated/dashboard'
    | '/_authenticated/despesas'
    | '/_authenticated/importar'
    | '/_authenticated/inicio'
    | '/_authenticated/investimentos'
    | '/_authenticated/lista-compras'
    | '/_authenticated/nova-senha'
    | '/_authenticated/personalizacao'
    | '/_authenticated/receitas'
    | '/_authenticated/usuarios'
    | '/oauth/google-drive/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OauthGoogleDriveReturnRoute: typeof OauthGoogleDriveReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/backup': {
      id: '/_authenticated/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthenticatedBackupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cartoes': {
      id: '/_authenticated/cartoes'
      path: '/cartoes'
      fullPath: '/cartoes'
      preLoaderRoute: typeof AuthenticatedCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compartilhar': {
      id: '/_authenticated/compartilhar'
      path: '/compartilhar'
      fullPath: '/compartilhar'
      preLoaderRoute: typeof AuthenticatedCompartilharRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conta': {
      id: '/_authenticated/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof AuthenticatedContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/investimentos': {
      id: '/_authenticated/investimentos'
      path: '/investimentos'
      fullPath: '/investimentos'
      preLoaderRoute: typeof AuthenticatedInvestimentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lista-compras': {
      id: '/_authenticated/lista-compras'
      path: '/lista-compras'
      fullPath: '/lista-compras'
      preLoaderRoute: typeof AuthenticatedListaComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nova-senha': {
      id: '/_authenticated/nova-senha'
      path: '/nova-senha'
      fullPath: '/nova-senha'
      preLoaderRoute: typeof AuthenticatedNovaSenhaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personalizacao': {
      id: '/_authenticated/personalizacao'
      path: '/personalizacao'
      fullPath: '/personalizacao'
      preLoaderRoute: typeof AuthenticatedPersonalizacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/receitas': {
      id: '/_authenticated/receitas'
      path: '/receitas'
      fullPath: '/receitas'
      preLoaderRoute: typeof AuthenticatedReceitasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/oauth/google-drive/return': {
      id: '/oauth/google-drive/return'
      path: '/oauth/google-drive/return'
      fullPath: '/oauth/google-drive/return'
      preLoaderRoute: typeof OauthGoogleDriveReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBackupRoute: typeof AuthenticatedBackupRoute
  AuthenticatedCartoesRoute: typeof AuthenticatedCartoesRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCompartilharRoute: typeof AuthenticatedCompartilharRoute
  AuthenticatedContaRoute: typeof AuthenticatedContaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedInvestimentosRoute: typeof AuthenticatedInvestimentosRoute
  AuthenticatedListaComprasRoute: typeof AuthenticatedListaComprasRoute
  AuthenticatedNovaSenhaRoute: typeof AuthenticatedNovaSenhaRoute
  AuthenticatedPersonalizacaoRoute: typeof AuthenticatedPersonalizacaoRoute
  AuthenticatedReceitasRoute: typeof AuthenticatedReceitasRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBackupRoute: AuthenticatedBackupRoute,
  AuthenticatedCartoesRoute: AuthenticatedCartoesRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCompartilharRoute: AuthenticatedCompartilharRoute,
  AuthenticatedContaRoute: AuthenticatedContaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedInvestimentosRoute: AuthenticatedInvestimentosRoute,
  AuthenticatedListaComprasRoute: AuthenticatedListaComprasRoute,
  AuthenticatedNovaSenhaRoute: AuthenticatedNovaSenhaRoute,
  AuthenticatedPersonalizacaoRoute: AuthenticatedPersonalizacaoRoute,
  AuthenticatedReceitasRoute: AuthenticatedReceitasRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OauthGoogleDriveReturnRoute: OauthGoogleDriveReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
